#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check
    
lists:
    type       : rest
    resource   : App\Controller\ListController
    prefix     : api